export const REGIONS = [
  // Mainland China
  {
    id: "beijing",
    name: "Beijing",
    chineseName: "北京",
    type: "mainland",
    lat: 39.9, lng: 116.4,
    accent: "Standard Mandarin (普通话) with heavy 儿化 (r-sounds). Beijing speech is the basis for standard Mandarin but locals add 'r' to the end of many words — 'nàr' instead of 'nà'.",
    culture: "Capital city culture — formal, proud, historically rich. Home of the Forbidden City, hutongs, and Peking duck.",
    food: ["北京烤鸭 (Běijīng kǎoyā) — Peking duck", "炸酱面 (zhájiàng miàn) — noodles with bean paste", "豆汁 (dòuzhī) — fermented mung bean drink"],
    scenarios: ["Visiting the Forbidden City", "Ordering Peking duck", "Taking the subway"],
    tip: "Locals are direct and proud of their city. Complimenting Beijing will go a long way.",
  },
  {
    id: "shanghai",
    name: "Shanghai",
    chineseName: "上海",
    type: "mainland",
    lat: 31.2, lng: 121.5,
    accent: "Mandarin with Wu dialect influence. Softer tones, faster pace. Many older locals mix Shanghainese into conversation.",
    culture: "Cosmopolitan and fast-paced. Fashion, finance, and food capital. Mix of East and West.",
    food: ["小笼包 (xiǎolóngbāo) — soup dumplings", "生煎包 (shēngjiān bāo) — pan-fried buns", "红烧肉 (hóngshāo ròu) — red braised pork"],
    scenarios: ["Ordering soup dumplings", "Shopping on Nanjing Road", "Taking the Maglev"],
    tip: "Shanghai locals are fashion-conscious and internationally minded. English is widely spoken but Mandarin is appreciated.",
  },
  {
    id: "chengdu",
    name: "Chengdu",
    chineseName: "成都",
    type: "mainland",
    lat: 30.6, lng: 104.1,
    accent: "Sichuan dialect influence — flatter tones, 'n' and 'l' merge, very distinctive cadence. Considered funny and endearing by other Chinese people.",
    culture: "Relaxed, foodie culture. Famous for giant pandas, teahouses, and taking life slow.",
    food: ["火锅 (huǒguō) — spicy hotpot", "麻婆豆腐 (mápó dòufu) — mapo tofu", "担担面 (dàndàn miàn) — dan dan noodles"],
    scenarios: ["Ordering hotpot", "Visiting a teahouse", "Seeing pandas"],
    tip: "Chengdu people are warm and laid-back. Don't be surprised if a meal lasts 3 hours — that's the point.",
  },
  {
    id: "guangzhou",
    name: "Guangzhou",
    chineseName: "广州",
    type: "mainland",
    lat: 23.1, lng: 113.3,
    accent: "Heavy Cantonese influence. Many locals prefer Cantonese and may switch mid-sentence. Mandarin tones are flatter than standard.",
    culture: "Business-focused, food obsessed. Dim sum culture is deeply rooted here.",
    food: ["点心 (diǎnxīn) — dim sum", "白切鸡 (báiqiē jī) — white cut chicken", "肠粉 (chángfěn) — rice noodle rolls"],
    scenarios: ["Dim sum brunch", "Haggling at a market", "Business meeting"],
    tip: "Cantonese is king here. Learning even one Cantonese phrase like '唔該' (m̀h gōi — thank you) will delight locals.",
  },
  {
    id: "xian",
    name: "Xi'an",
    chineseName: "西安",
    type: "mainland",
    lat: 34.3, lng: 108.9,
    accent: "Northwestern accent — stronger consonants, different vowel sounds, slower and more deliberate speech.",
    culture: "Ancient capital, home of the Terracotta Warriors. Muslim Quarter is a major cultural landmark.",
    food: ["肉夹馍 (ròu jiā mó) — Chinese burger", "羊肉泡馍 (yángròu pào mó) — lamb soup with bread", "凉皮 (liángpí) — cold skin noodles"],
    scenarios: ["Visiting Terracotta Warriors", "Eating in the Muslim Quarter", "Bargaining at the market"],
    tip: "Xi'an has a large Muslim Hui community. Be respectful of halal dietary practices when eating out.",
  },
  {
    id: "harbin",
    name: "Harbin",
    chineseName: "哈尔滨",
    type: "mainland",
    lat: 45.8, lng: 126.5,
    accent: "Northeastern (东北) accent — heavy 'r' sounds everywhere, fast and loud, considered very funny by other Chinese. Often called the most 'authentic' Mandarin by linguists.",
    culture: "Russian influence, ice festival, extremely cold winters. Hearty food and hospitality.",
    food: ["锅包肉 (guōbāo ròu) — sweet and sour pork", "红肠 (hóngcháng) — Harbin sausage", "杀猪菜 (shāzhū cài) — pork stew"],
    scenarios: ["Ice and Snow Festival", "Russian architecture tour", "Winter street food"],
    tip: "Dongbei people are famously warm and loud. Expect big portions, strong liquor, and genuine hospitality.",
  },
  // Taiwan
  {
    id: "taipei",
    name: "Taipei",
    chineseName: "台北",
    type: "taiwan",
    lat: 25.0, lng: 121.5,
    accent: "Traditional characters, softer pronunciation, different slang. '厲害' (lìhài) means cool/awesome. Speech is generally gentler than mainland Mandarin.",
    culture: "Night market culture, extremely polite society, blend of Chinese, Japanese, and indigenous influences.",
    food: ["臭豆腐 (chòu dòufu) — stinky tofu", "珍珠奶茶 (zhēnzhū nǎichá) — bubble tea (invented here)", "牛肉麵 (niúròu miàn) — beef noodle soup"],
    scenarios: ["Night market food crawl", "Ordering bubble tea", "MRT navigation"],
    tip: "Taiwan uses Traditional characters, not Simplified. Menus and signs will look different from mainland China.",
  },
  // Diaspora
  {
    id: "vancouver",
    name: "Vancouver",
    chineseName: "温哥华",
    type: "diaspora",
    lat: 49.3, lng: -123.1,
    accent: "Mix of mainland and Cantonese-influenced Mandarin. Many speakers mix English words into Mandarin naturally.",
    culture: "Large Cantonese and mainland Chinese communities, especially in Richmond. Very food-focused diaspora.",
    food: ["海鲜 (hǎixiān) — fresh seafood", "茶餐厅 (chá cāntīng) — HK-style cafe food", "港式点心 (gǎngshì diǎnxīn) — Cantonese dim sum"],
    scenarios: ["Family dinner with Chinese-Canadian relatives", "Richmond Night Market", "Ordering dim sum"],
    tip: "In Vancouver's Chinese community, Cantonese is still widely spoken by older generations. Mandarin is more common with younger and mainland immigrants.",
  },
  {
    id: "singapore",
    name: "Singapore",
    chineseName: "新加坡",
    type: "diaspora",
    lat: 1.35, lng: 103.82,
    accent: "Singaporean Mandarin mixed with Singlish — unique rhythm and intonation. Common filler words like 'lah', 'leh', 'lor' mixed in.",
    culture: "Multicultural society — Chinese, Malay, Indian, Western all coexist. Food is a national obsession.",
    food: ["海南鸡饭 (Hǎinán jīfàn) — Hainanese chicken rice", "肉骨茶 (ròugǔchá) — bak kut teh pork rib soup", "辣椒螃蟹 (làjiāo pángxiè) — chilli crab"],
    scenarios: ["Hawker centre lunch", "Business meeting", "Ordering at a kopitiam"],
    tip: "Singaporean Mandarin is called 华语 (Huáyǔ) not 普通话 (Pǔtōnghuā). It's mutually intelligible but has unique vocabulary and a distinctive rhythm.",
  },
];

export const REGION_TYPES = {
  mainland: { label: "Mainland China", color: "#d4a843" },
  taiwan: { label: "Taiwan", color: "#68d391" },
  diaspora: { label: "Diaspora", color: "#76e4f7" },
};